### ISSUE TITLE
"Error: Method plasma_getConfig not supported" when trying machine gun

### ISSUE THREAD

**Issue by johba37** [leapdao/leap-guardian#38]
```
a1708-2:leap-guardian johba$ NUM=5 NODE_URL=http://localhost:8545 PRIV_KEY=0x00..11 node scripts/machineGun.js
Leap node:  http://localhost:8545
(node:31700) UnhandledPromiseRejectionWarning: Error: Method plasma_getConfig not supported.
    at getResult (/Users/johba/dev/leap-guardian/node_modules/ethers/providers/json-rpc-provider.js:40:21)
    at exports.XMLHttpRequest.request.onreadystatechange (/Users/johba/dev/leap-guardian/node_modules/ethers/utils/web.js:111:30)
    at exports.XMLHttpRequest.dispatchEvent (/Users/johba/dev/leap-guardian/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/johba/dev/leap-guardian/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Users/johba/dev/leap-guardian/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by johba37** [comment]
used the wrong endpoint 🤦‍♂
